# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'webRTC_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleWebRTC'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Crashlytics'

  # Pods for webRTC_iOS

  target 'webRTC_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'webRTC_iOSUITests' do
    # Pods for testing
  end

end
